export const CANDIDATE_STATUS = {
  NEW: "NEW",

  AI_PROCESSING: "AI_PROCESSING",

  AI_PROCESSED: "AI_PROCESSED",

  CONTACT_PENDING: "CONTACT_PENDING",

  CONTACTED: "CONTACTED",

  FOLLOW_UP: "FOLLOW_UP",

  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",

  INTERVIEW_COMPLETED: "INTERVIEW_COMPLETED",

  TASK_ASSIGNED: "TASK_ASSIGNED",

  TASK_SUBMITTED: "TASK_SUBMITTED",

  TASK_REVIEW: "TASK_REVIEW",

  SELECTED: "SELECTED",

  DROPPED: "DROPPED",
};

export const STATUS_VALUES =
  Object.values(CANDIDATE_STATUS);