export const DROP_REASONS = {
  CALL_NOT_PICKED: "CALL_NOT_PICKED",

  NOT_INTERESTED: "NOT_INTERESTED",

  NOT_QUALIFIED: "NOT_QUALIFIED",

  COMMUNICATION_ISSUE: "COMMUNICATION_ISSUE",

  TECHNICAL_WEAK: "TECHNICAL_WEAK",

  INTERVIEW_NO_SHOW: "INTERVIEW_NO_SHOW",

  TASK_FAILED: "TASK_FAILED",

  OTHER: "OTHER",
};

export const DROP_REASON_VALUES =
  Object.values(DROP_REASONS);