export const INTEREST_STATUS = {
  INTERESTED: "INTERESTED",

  WILL_CALL_BACK: "WILL_CALL_BACK",

  NEEDS_FOLLOW_UP:
    "NEEDS_FOLLOW_UP",
};

export const INTEREST_STATUS_VALUES =
  Object.values(INTEREST_STATUS);