export const TIMELINE_EVENTS = {
  RESUME_UPLOADED: "RESUME_UPLOADED",

  AI_PROCESSED: "AI_PROCESSED",

  CANDIDATE_ASSIGNED: "CANDIDATE_ASSIGNED",

  PROFILE_UPDATED: "PROFILE_UPDATED",

  STATUS_CHANGED: "STATUS_CHANGED",

  CALL_LOGGED: "CALL_LOGGED",

  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",

  TASK_ASSIGNED: "TASK_ASSIGNED",

  SELECTED: "SELECTED",

  DROPPED: "DROPPED",
};